### ISSUE TITLE
Discord links seem expired or borken

### ISSUE THREAD

**Issue by mikemainguy** [fireproof-storage/fireproof#301]
Not sure if this is the right place, but when I try to join the discord, it says it's either expired or I don't have permission.

**Comment by mikemainguy** [comment]
https://discord.gg/cCryrNHePH

<img width="469" alt="Screenshot 2024-10-19 at 12 28 34 PM" src="https://github.com/user-attachments/assets/a0578925-e391-4551-9640-b6ab5bc1c960">

**Comment by jchris** [comment]
thank you, maybe they only last a year I'll update them

**Comment by jchris** [comment]
ok I fixed it, please let me know if that doesn't help
